{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "viewbinding",
    "version": "8.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.7.2.aar",
          "url": "viewbinding-8.7.2.aar",
          "size": 1860,
          "sha512": "0bdcd61f9761ac9fee1e50216731e767a485c4a9898caa0b28bb9d148471a5deef79fc79d130d97f6da5bf9565a953372a76fcef15fa72ad6a5f12f4759d6a75",
          "sha256": "2a9c3409ec21257597a85a3d204b0c7ed06be5028ae57587daa94e90c91e1a01",
          "sha1": "91e8ac129a066343635f78b59c4b90aee47cbf11",
          "md5": "fda053d4f4ea062cffb655112f0dc2f0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.7.2.aar",
          "url": "viewbinding-8.7.2.aar",
          "size": 1860,
          "sha512": "0bdcd61f9761ac9fee1e50216731e767a485c4a9898caa0b28bb9d148471a5deef79fc79d130d97f6da5bf9565a953372a76fcef15fa72ad6a5f12f4759d6a75",
          "sha256": "2a9c3409ec21257597a85a3d204b0c7ed06be5028ae57587daa94e90c91e1a01",
          "sha1": "91e8ac129a066343635f78b59c4b90aee47cbf11",
          "md5": "fda053d4f4ea062cffb655112f0dc2f0"
        }
      ]
    }
  ]
}
